version: "3"
services:
    mlsb-bot:
        environment:
            - ADMIN=$ADMIN
            - DBNAME=$DBNAME
            - DBPW=$DBPW
            - DBUSER=$DBUSER
            - LOCAL=$LOCAL
            - MONGODB_URI=$MONGODB_URI
            - PAGE_ACCESS_TOKEN=$PAGE_ACCESS_TOKEN
            - PASSWORD=$PASSWORD
            - PLATFORM=$PLATFORM
            - URI=$URI
            - VERIFY_TOKEN=$VERIFY_TOKEN 
        restart: always
        build: .
        ports:
            - 8081:8081
        volumes:
            - .:/app
        depends_on:
            - postgres
            - redis
        command: >
            gunicorn -b 0.0.0.0:8081
                --access-logfile -
                --reload
                "runserver:app"

    mongodb:
      image: mongo:latest
      container_name: "mongodb"
      environment:
       - MONGO_DATA_DIR=/usr/data/db
       - MONGO_LOG_DIR=/dev/null
      volumes:
       - 'mongo:/data'
      ports:
       - 27017:27017
      command: mongod --smallfiles --logpath=/dev/null # --quiet

volumes:
    name: mongo