name: Docker Publish Image Custom

on:
  push:
    branches: 
      - master
      - development

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag mlsbca/mlsb-bot:${GITHUB_REF##*/}
    - name: Login into Docker hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish Docker image
      run: docker push mlsbca/mlsb-bot:${GITHUB_REF##*/}
